import type { Metadata } from "next";
// Import fonts for project Inter, Poppins, and Jetbrains Mono
import { Inter, Poppins, JetBrains_Mono } from "next/font/google";
// Import Global Styles for tailwind and shadcn
import "./globals.css";
import NavigationBar from "@/components/layout/NavigationBar";
import { Toaster, TooltipProvider } from "@/components/ui";
import NavigationClientWrapper from "@/components/layout/NavigationBar/NavigationClientWrapper";
import { Footer } from "@/components/layout";

// Configure Google Fonts For Use

// Inter
export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "700"],
});
// Poppins
export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["500", "700"],
});
// Jet Brains Mono
export const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "700", "800"],
});

// Project Metadata
export const metadata: Metadata = {
  title: "Tyodev | Professional Web Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable} ${jetBrainsMono.variable} dark`}
    >
      <body className="bg-page-background text-text-main">
        <main className="relative min-h-screen flex flex-col">
          {/* grain overlay */}
          <div
            className="pointer-events-none absolute inset-0 z-10 opacity-[0.03]"
            style={{
              backgroundImage: "url('/grain.jpeg')",
              backgroundRepeat: "repeat",
            }}
          />

          <NavigationClientWrapper>
            <Toaster />

            <TooltipProvider>
              {/* page content grows */}
              <div className="relative z-30 flex-1">{children}</div>
            </TooltipProvider>
          </NavigationClientWrapper>

          {/* footer sticks to bottom */}
          <Footer />
        </main>
      </body>
    </html>
  );
}
