import type { Metadata } from "next";
// Import fonts for project Inter, Poppins, and Jetbrains Mono
import { Inter, Poppins, JetBrains_Mono } from "next/font/google";
// Import Global Styles for tailwind and shadcn
import "./globals.css";
import NavigationBar from "@/components/layout/NavigationBar";
import { TooltipProvider } from "@/components/ui";

// Configure Google Fonts For Use

// Inter
export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "700"],
});
// Poppins
export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["500", "700"],
});
// Jet Brains Mono
export const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "700"],
});

// Project Metadata
export const metadata: Metadata = {
  title: "Tyodev | Professional Web Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable} ${jetBrainsMono.variable} dark`}
    >
      <body className="bg-page-background text-text-main">
        <main className="relative">
          <div
            className="pointer-events-none min-w-full min-h-full absolute inset-0 z-10 opacity-[0.03]"
            style={{
              backgroundImage: "url('/grain.jpeg')",
              backgroundRepeat: "repeat",
            }}
          />
          <NavigationBar />
          <TooltipProvider>
            <div className="relative z-30">{children}</div>
          </TooltipProvider>
        </main>
      </body>
    </html>
  );
}
